### ISSUE TITLE
Readme recommends TypeScript Vue Plugin (Volar) and take over mode seems already discarded.

### ISSUE THREAD

**Issue by wildtang** [heliomarpm/electron-vuevite-quick-start#19]
The readme recommends 
[TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) and take over mode already discarded, Nowadays the Vue recommends is Vue - Official plugin.

Could you update it, thanks!

**Comment by heliomarpm** [comment]
Updated recommendations

**Comment by heliomarpm** [comment]
Please leave me a star
